dist: xenial
sudo: required
language: c

cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    packages:
    - gcc-multilib
env:
  global:
  - NJOBS=2
  - OPAMROOTISOK="true"
  - OPAMYES="true"
  - OPAMJOBS="2"
  - COMPILER="4.07.1+32bit"
  - BASE_OPAM="camlp5 dune elpi"

install:
- echo "yes" | sudo add-apt-repository ppa:ansible/bubblewrap
- sudo apt-get update -qq
- sudo apt-get install -qq bubblewrap
- sudo curl -sL https://github.com/ocaml/opam/releases/download/2.0.2/opam-2.0.2-x86_64-linux -o /usr/bin/opam
- sudo chmod 755 /usr/bin/opam
- opam init -c "$COMPILER"
- opam switch set "$COMPILER"
- eval $(opam env)
- opam install $BASE_OPAM $EXTRA_OPAM # yojson ppx_deriving_yojson
- opam list
- opam update
- opam config var root
- ./toolchain-setup.sh
- opam list
- make coq-get
- make coq-build

script:
- echo 'Building JsCoq...' && echo -en 'travis_fold:start:jscoq.build\\r'
- ./build.sh
- git submodule update --remote
- cd ui-external/CodeMirror && npm install
- echo -en 'travis_fold:end:jscoq.build\\r'
