dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib
env:
  global:
  - NJOBS=2
  # - COQ_REPOS=git://scm.gforge.inria.fr/coq/coq.git
  - COQ_REPOS="https://github.com/coq/coq.git"
  # system is == 4.02.3
  - COMPILER="4.04.2+32bit"
  - COQ_BRANCH="v8.7"
  - COQ_VERSION="v8.7"
  - BASE_OPAM="camlp5 yojson ppx_import ppx_deriving_yojson js_of_ocaml js_of_ocaml-ppx js_of_ocaml-lwt"
  # Main test suites
  # matrix:
  # - TEST_TARGET="x86_32-linux"
  # - TEST_TARGET="x86_64-linux"

install:
- "[ -e .opam ] || opam init -j ${NJOBS} --compiler=${COMPILER} -n -y"
- eval $(opam config env)
- opam update
- opam config var root
- opam install -j ${NJOBS} -y ${BASE_OPAM} ${EXTRA_OPAM}
- opam list
- mkdir -p ${HOME}/external && pushd ${HOME}/external
- git clone --depth=3 -b ${COQ_BRANCH} ${COQ_REPOS} coq-${COQ_VERSION}+32bit
- cd coq-${COQ_VERSION}+32bit
- ./configure -local -native-compiler no -coqide no
- make -j ${NJOBS}
- make -j ${NJOBS} byte
- popd

script:
- echo 'Building JsCoq...' && echo -en 'travis_fold:start:jscoq.build\\r'
- ./build.sh
- git submodule update --remote
- cd ui-external/CodeMirror && npm install
- echo -en 'travis_fold:end:jscoq.build\\r'
